repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.2.0
  hooks:
    - id: reorder-python-imports
      language_version: python3.10
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
    - id: black
      args: [--target-version, py310, --experimental-string-processing]
      language_version: python3.10
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: trailing-whitespace